# See https://eng.inky.wtf/docs/technical/git/pre-commit for info on how to edit this file.
- id: check-for-epoch-bump
  name: Checks that package yaml files have epoch bumps compared to main
  description: Helps to prevent any accidental forgotten epoch bumps so packages rebuild properly
  entry: scripts/check-for-epoch-bump.sh
  language: script
  verbose: true
  stages:
    - pre-commit
    - manual
  types:
    - yaml
- id: shellcheck-run-steps
  name: shellcheck run steps
  description: run shellcheck on each "run" step in a melange pipeline
  entry: shellcheck-run-steps
  language: python
  stages:
    - pre-commit
    - manual
  types:
    - yaml
- id: check-pipeline-name-only-steps
  name: check pipeline name-only steps
  description: check that pipeline steps don't have only a name without uses or other details
  entry: check-pipeline-name-only-steps
  language: python
  stages:
    - pre-commit
    - manual
  types:
    - yaml
