package:
  name: test-package-good
  version: "1.0.0"
  epoch: 0
  description: "Test package with correctly formatted pipeline steps"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - go-fips-1.22

pipeline:
  - uses: test/go-fips-check  # GOOD: Uses 'uses' instead of 'name'
  - name: "Configure build"
    uses: autoconf/configure  # GOOD: Has both name and uses
    with:
      opts: --enable-shared
  - uses: autoconf/make  # GOOD: Just uses is fine
  - name: "Run custom script"  # GOOD: Has name and runs
    runs: |
      echo "Building package"
      make install

test:
  pipeline:
    - uses: test/go-fips-check  # GOOD: Properly uses 'uses'
    - name: "Test daemon output"
      uses: test/daemon-check-output  # GOOD: Has both name and uses
      with:
        expected_output: |
          Server started
    - uses: test/emptypackage  # GOOD: Just uses

subpackages:
  - name: test-subpkg-good
    description: "Subpackage with correct pipeline"
    pipeline:
      - uses: split/dev  # GOOD: Uses 'uses'
      - name: "Move files"
        runs: |  # GOOD: Has name and runs
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv usr/bin/tool ${{targets.subpkgdir}}/usr/bin/
    test:
      pipeline:
        - uses: test/emptypackage  # GOOD: Uses 'uses' in test section